#!/bin/bash

# Execute a command with Composer
#
# usage: ynh_composer_exec [--user=$app] [--phpversion=phpversion] [--workdir=$final_path] --commands="commands"
# | arg: -u, --user - User to perform the action with
# | arg: -v, --phpversion - PHP version to use with composer
# | arg: -w, --workdir - The directory from where the command will be executed. Default $final_path.
# | arg: -c, --commands - Commands to execute.
ynh_composer_exec () {
	# Declare an array to define the options of this helper.
	local legacy_args=uvwc
	declare -Ar args_array=( [u]=user= [v]=phpversion= [w]=workdir= [c]=commands= )
	local user
	local phpversion
	local workdir
	local commands
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"
	user="${user:-$app}"
	phpversion="${phpversion:-7.0}"
	workdir="${workdir:-$final_path}"

	exec_as $user COMPOSER_HOME="$workdir/.composer" \
		php${phpversion} "$workdir/composer.phar" $commands \
		-d "$workdir" --no-interaction --ansi
}

# Install and initialize Composer in the given directory
#
# usage: ynh_install_composer [--user=$app] [--phpversion=phpversion] [--workdir=$final_path] [--install_args="--optimize-autoloader"]
# | arg: -u, --user - User to perform the action with
# | arg: -v, --phpversion - PHP version to use with composer
# | arg: -w, --workdir - The directory from where the command will be executed. Default $final_path.
# | arg: -a, --install_args - Additional arguments provided to the composer install. Argument --no-dev already included
ynh_install_composer () {
	# Declare an array to define the options of this helper.
	local legacy_args=uvwa
	declare -Ar args_array=( [u]=user= [v]=phpversion= [w]=workdir= [a]=install_args=)
	local user
	local phpversion
	local workdir
	local install_args
	# Manage arguments with getopts
	ynh_handle_getopts_args "$@"
	user="${user:-$app}"
	workdir="${workdir:-$final_path}"
	phpversion="${phpversion:-7.0}"
	install_args="${install_args:-}"

		curl -sS https://getcomposer.org/installer \
		| exec_as $user COMPOSER_HOME="$workdir/.composer" \
			php${phpversion} -- --install-dir="$workdir" \
		|| ynh_die "Unable to install Composer."

	# update dependencies to create composer.lock
	#ynh_composer_exec --user=$user --phpversion="${phpversion}" --workdir="$workdir" --commands="install --no-dev $install_args" \
	#	|| ynh_die "Unable to update core dependencies with Composer."
}
