#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# ...
#=================================================
if [ $new_path = "/" ]; then
	if [ $old_path = "/" ]; then
		# FIXMEhelpers2.1: ynh_replace used with positional args. Please add the keywords: --match=, --replace=, --file=
ynh_replace "://$old_domain" "://$new_domain" "$install_dir/config.php"
	else
		# FIXMEhelpers2.1: ynh_replace used with positional args. Please add the keywords: --match=, --replace=, --file=
ynh_replace "://$old_domain$old_path" "://$new_domain" "$install_dir/config.php"
	fi
else
        if [ $old_path = "/" ]; then
                # FIXMEhelpers2.1: ynh_replace used with positional args. Please add the keywords: --match=, --replace=, --file=
ynh_replace "://$old_domain" "://$new_domain$new_path" "$install_dir/config.php"
        else
                # FIXMEhelpers2.1: ynh_replace used with positional args. Please add the keywords: --match=, --replace=, --file=
ynh_replace "://$old_domain$old_path" "://$new_domain$new_path" "$install_dir/config.php"
        fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
