#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

if [ $new_path = "/" ]; then
	if [ $old_path = "/" ]; then
		ynh_replace --match="://$old_domain" --replace="://$new_domain" --file="$install_dir/config.php"
	else
		ynh_replace --match="://$old_domain$old_path" --replace="://$new_domain" --file="$install_dir/config.php"
	fi
else
        if [ $old_path = "/" ]; then
                ynh_replace --match="://$old_domain" --replace="://$new_domain$new_path" --file="$install_dir/config.php"
        else
                ynh_replace --match="://$old_domain$old_path" --replace="://$new_domain$new_path" --file="$install_dir/config.php"
        fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
