#!/bin/bash

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# Delete user
ynh_system_user_delete $app

# Remove sources
ynh_secure_remove "/tmp/$app"
ynh_secure_remove "/var/www/$app"
ynh_secure_remove "/opt/${app}_composer"

# Remove nginx and PHP-FPM files and restart services
ynh_remove_nginx_config
ynh_remove_fpm_config
sudo service nginx reload
sudo service php5-fpm reload

### MySQL ###
# If a MySQL database is used:
# # Drop MySQL database and user
dbname=$app
dbuser=$app
ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true
### MySQL end ###
